nw_comics/Artigos/urls.py
from django.urls import path
from . import views

app_name = 'Artigos'
urlpatterns = [
    path('', views.meus_artigos, name='meus_artigos'),
    path('publicar', views.publicar, name='publicar')
]

nw_comics/Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'
urlpatterns = [
    path('index/', views.index, name='index'),
]

nw_comics/Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('login/', views.do_login, name='do_login'),
    path('logout/', views.do_logout, name='do_logout'),
    path('cadastro/', views.casdastro, name='cadastro')
]

nw_comics/nw_comics/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('Login.urls')),
    path('session/', include('Home.urls')),
    path('artigos/', include('Artigos.urls'))
]

nw_comics/Artigos/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from Login.models import Usuarios

# Create your models here.

class Artigos(models.Model):
    titulo = models.TextField()
    genero = models.CharField(max_length=255)
    resumo = models.TextField()
    capa = models.ImageField()
    usuario = models.ForeignKey('auth.User', on_delete=CASCADE)

class Capitulos(models.Model):
    artigo = models.ForeignKey(Artigos, on_delete=CASCADE)
    texto = models.TextField()
    imagem1 = models.ImageField()
    imagem2 = models.ImageField()
    imagem3 = models.ImageField()

nw_comics/Login/models.py
from django.db import models

# Create your models here.

class Usuarios(models.Model):
    auth_user = models.OneToOneField('auth.User', on_delete=models.PROTECT, null=True)
    admin = models.BooleanField(default=False)
    ativado = models.BooleanField(default=False)
    data_nascimento = models.TextField()

nw_comics/Artigos/forms.py
# Imports do Django
from django.forms import ModelForm

# Imports do mesmo App
from .models import Artigos


class ArtigosForm(ModelForm):
    class Meta:
        model = Artigos
        fields = '__all__'

nw_comics/Artigos/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import Artigos
from .forms import ArtigosForm

# Create your views here.

@login_required(login_url='Login:do_login')
def meus_artigos(request):
    artigos = Artigos.objects.filter(usuario=request.user)
    return render(request, 'meus_artigos.html', {'artigos' : artigos})

@login_required(login_url='Login:do_login')
def publicar(request):
    if request.method == 'GET':
        form = ArtigosForm()
        return render(request, 'publicar.html')
    elif request.method == 'POST':
        try:
            titulo = request.POST['titulo']
            resumo = request.POST['resumo']
            capa = request.POST['capa']
            
            artigo = Artigos(titulo=titulo, resumo=resumo, capa=capa, usuario=request.user)
            artigo.save()

            context = {
                'mensagem' : 'Artigo cadastrado com sucesso!'
            }
        except:
            context = {
                'mensagem' : 'Erro ao cadastrar o artigo!'
            }

        return render(request, 'publicar.html', context=context)
        

nw_comics/Home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    slide1 = {
        'url' : 'the_witcher.jpg',
        'nome' : 'The Witcher'
    }
    slide2 = {
        'url' : 'stranger_things.jpeg',
        'nome' : 'Stranger Things'
    }
    slide3 = {
        'url' : 'the_100.jpg',
        'nome' : 'The 100'
    }

    context = {
        'slide1' : slide1,
        'slide2' : slide2,
        'slide3' : slide3
    }
    return render(request, 'home.html', context=context)

nw_comics/Login/views.py
from .backend import MyBackend
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from .models import Usuarios

# Create your views here.

def do_login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # Verifica o usuario
        if MyBackend.checkUser(username=username) == False:
            messages.warning(request, 'Usuario ou senha incorreto!')
            return render(request, 'login.html')
        else:
            # Verifica a senha
            if MyBackend.checkPassword(username=username, password=password) == False:
                messages.warning(request, 'Usuario ou senha incorreto!')
                return render(request, 'login.html')
            else:
                user = MyBackend.authenticate(username=username, password=password)
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('Home:index')

def do_logout(request):
    logout(request)
    return redirect('Home:index')

# Cadastro de usuario
def casdastro(request):
    if request.method == 'GET':
        context = {}
        return render(request, "cadastro.html", context)
    elif request.method == 'POST':
        form_user = UserCreationForm(request.POST)

        if form_user.is_valid():
            user = form_user.save()
            usuario = Usuarios(auth_user=user, admin=False, ativado=False, data_nascimento=request.POST['data'])
            usuario.save()
            return redirect('Home:index')
        else:
            for erro, msg in form_user.errors.items():
                messages.error(request, msg, extra_tags='danger')
            return render(request, "cadastro.html")

nw_comics/Artigos/templates/meus_artigos.html
{% extends 'base_home.html' %}
{% load static %}

{% block title %} Inicio {% endblock %}

{%block content%}
<div class="container">
    {% for artigo in artigos %}
        <div class="row justify-content-md-center">
            <div class="form-control col-md-2">
                <label class="form-control" for="">Titulo:</label>
                {{artigo.titulo}}
            </div>
            <div class="form-control col-md-5">
                <label class="form-control" for="">Resumo:</label>
                {{artigo.resumo}}
            </div>
            <div class="form-control col-md-2">
                <label class="form-control" for="">Capa:</label>
                {{artigo.capa}}
            </div>
        </div>
    {%endfor%}
</div>

<div class="container">
    <div class="row justify-content-md-center">
        
    </div>
</div>
{%endblock%}

nw_comics/Artigos/templates/publicar.html
{% extends 'base_home.html' %}
{% load static %}

{% block title %} Inicio {% endblock %}

{%block content%}
<div class="container">
    <h2>{{mensagem}}</h2>
    <form action="{% url 'Artigos:publicar' %}" method="POST">
        {% csrf_token %}
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                    <label class="form-control" for="id_titulo">Titulo:</label>
                    <input class="form-control" type="text" name="titulo" cols="40" rows="10" required="" id="id_titulo"></input>
                    <br>
                    <label class="form-control" for="id_resumo">Resumo:</label>
                    <textarea class="form-control" name="resumo" cols="40" rows="10" required="" id="id_resumo"></textarea>
                    <br>
                    <label class="form-control" for="id_capa">Capa:</label>
                    <input class="form-control" type="file" name="capa" accept="image/*" required="" id="id_capa">
                    <br>
                    <input type="submit" value="Cadastar Artigo">
            </div>
        </div>
    </form>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        
    </div>
</div>
{%endblock%}

nw_comics/Base/templates/base_home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NW Comics | {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">NW Comics</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Gêneros</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Popular</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Artigos:meus_artigos' %}">Meus Artigos</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Editar Perfil</a>
                    <a class="dropdown-item" href="#">Configurações</a>
                    <a class="dropdown-item" href="{% url 'Login:do_logout' %}">Logout</a>
                </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Login:do_login' %}">Login</a>
                </li>
            {% endif %}
          </ul>
        </div>
    </nav>


    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>   

</body>
</html>

nw_comics/Base/templates/base_login.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NW Comics | {% block title %}{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block head %}{% endblock %}
</head>
<body>

    {% block content %}

    {% endblock %}

</body>
</html>

nw_comics/Home/templates/home.html
{% extends 'base_home.html' %}
{% load static %}

{% block title %} Inicio {% endblock %}

{%block content%}
<div class="container">
    <div class="row justify-content-md-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="/static/Home/img/{{slide1.url}}" alt="{{slide1.nome}}">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/Home/img/{{slide2.url}}" alt="{{slide2.nome}}">
                    </div>
                    <div class="carousel-item">
                      <img class="d-block w-100" src="/static/Home/img/{{slide3.url}}" alt="{{slide3.nome}}">
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

nw_comics/Login/templates/cadastro.html
{% extends 'base_login.html' %}
{% load static %}

{% block head %}
<link href="{% static 'login/css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block title %} Login {% endblock %}

{%block content%}
<div class="container">
    <div class="row justify-content-md-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Icon -->
          <div class="fadeIn first">
            <img src="{% static '/login/img/logo.png' %}" id="icon" alt="NW Comics" />
          </div>
            <form action="{% url 'Login:cadastro' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="username" autofocus=""  required="" id="id_username" name="login" placeholder="login" class="fadeIn second">
                <input type="text" name="data" required="" id="id_data"  name="data" placeholder="Data de nascimento" class="fadeIn third">
                <input type="text" name="email" required="" id="id_email" name="email" placeholder="E-mail" class="fadeIn fourth">
                <input type="password" name="password1" required="" id="id_password1" name="password1" placeholder="Senha" class="fadeIn fifth">
                <input type="password" name="password2" required="" id="id_password2" name="password2" placeholder="Confirme sua senha" class="fadeIn sixth">

                <input type="submit" value="Cadastrar"></input>
            </form>

            <!-- Remind Passowrd -->
          <div id="formFooter">
            <a class="underlineHover" href="{% url 'Login:do_login' %}">Já tem uma conta? Clique aqui para entrar!</a>
          </div>
        </div> 
    </div>
</div>
{%endblock%}

nw_comics/Login/templates/login.html
{% extends 'base_login.html' %}
{% load static %}

{% block head %}
<link href="{% static 'login/css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %} Login {% endblock %}

{%block content%}
<div class="container">
    <div class="row justify-content-md-center">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<div class="container">
    <!--<div class="row justify-content-md-center">
        <div class="col col-lg-2">
            <form action="{% url 'Login:cadastro' %}">
                <input type="text" name="username" autofocus=""  required="" id="id_username" name="login" placeholder="login">
                <input type="text" name="data" required="" id="id_data"  name="data" placeholder="Data de nascimento">
                <input type="email" name="email" required="" id="id_email" name="email" placeholder="E-mail">
                <input type="password" name="password_1" required="" id="id_password_1" name="password" placeholder="Senha">
                <input type="password" name="password_2" required="" id="id_password_2" name="password_2" placeholder="Confirme sua senha">

                <button type="submit">Cadastrar</button>
            </form>
        </div> 
    </div>-->

    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
      
          <!-- Icon -->
          <div class="fadeIn first">
            <img src="{% static '/login/img/logo.png' %}" id="icon" alt="NW Comics" />
          </div>
      
          <!-- Login Form -->
          <form action="{% url 'Login:do_login' %}" method='POST'>
            {% csrf_token %}
            <input type="text" name="username" id="id_username" class="fadeIn second" name="login" placeholder="login">
            <input type="password" name="password" id="id_password" class="fadeIn third" name="login" placeholder="password">
            <input type="submit" class="fadeIn fourth" value="Log In">
          </form>
          
          <!-- Remind Passowrd -->
          <div id="formFooter">
            <a class="underlineHover" href="#">Forgot Password?</a>
            <a class="underlineHover" href="{% url 'Login:cadastro' %}">Ainda não tem uma conta? Clique aqui para criar!</a>
          </div>
      
        </div>
      </div>
</div>
{%endblock%}